apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn-system
data:
  default-resource.yaml: |
    "backup-target": "nfs://<IP>:/longhorn-backup/"
    "backupstore-poll-interval": "180"
