repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: longhorn
    url: https://charts.longhorn.io

---
releases:
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.15.2

  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.10.0
